### ISSUE TITLE
[Addressables] Loading scene by a single AssetReference multiple times throws an error

### ISSUE THREAD

**Issue by miltoncandelero** [mygamedevtools/scene-loader#34]
![image](https://github.com/mygamedevtools/scene-loader/assets/15253010/fd6802ef-bf05-4624-9daf-c346f2b19f94)

It seems that the loading screen is dismissed before the old scene is unloaded so if you try to return to the scene you just left the scene is still loaded and being unloaded and your transition fails

I will investigate further

Edit: I have trouble replicating it in my webgl builds... maybe it's something with the editor?

**Comment by thatjoaoguy** [comment]
Hi @miltoncandelero , thank you for your report.

Can you share more details about how you got this error? By the logs it seems you are using the addressable scene manager and the unitask scene loader, is that right? If possible, please also share some code snippets with the scene loading functionality.

**Comment by miltoncandelero** [comment]
Oh, god, it took me forever but I found  the issue 🤦 

In my scene management singleton thingy, I cache this

```cs
transitionSceneInfoCache = new LoadSceneInfoAssetReference(transitionSceneAddresable);
```

If I try to go quickly back and forth, I trigger another transition scene before the previous one is done, but the cache tries to load twice the scene and it explodes.
If I always make a new SceneInfo there is no problems.

Probably me using it wrong 😅 

Edit: also happens if my `transitionSceneAddresable` is _exactly_ the same reference.
I had the asset reference in my singleton thingy as a "defaultTransition" , so the reference is exactly the same. 
If pass a "fresh" reference of the same asset, it doesn't trigger the error

---

Very ~~basic~~ naive code for replicating this:

```cs
	public AssetReference targetScene;
	public AssetReference transitionScene;
	public static AssetReference cache;
	public Button button;


	public void Transition()
	{
		var sceneInfo = new LoadSceneInfoAssetReference(targetScene);

		if (cache == null)
		{
			cache = transitionScene;
		}

		SceneManagerSingleton.Instance.Loader.TransitionToScene(sceneInfo, new LoadSceneInfoAssetReference(cache), UnityEngine.SceneManagement.SceneManager.GetActiveScene());
		button.interactable = false;
	}
```

You will need a transition that manually triggers the Load finished state but allows you to change transition before setting the state.

Attached my repro project. Closing the issue as it is just me trying to outsmart the system and being dumb in the process 🤦 

[repo.zip](https://github.com/mygamedevtools/scene-loader/files/15472314/repo.zip)

**Comment by thatjoaoguy** [comment]
Hey @miltoncandelero, thank you for the repro project.

You were not wrong to expect the scene loader to work in the given context, it was supposed to. I've tested your repro project and **successfully reproduced** the issue with `AssetReferences`, but if we replace the `ILoadSceneInfo` objects with the scene's **addressable address** (`LoadSceneInfoName`), the scene transition works as expected:

```cs
public string targetScene;
public string transitionScene;
public static string cache;
public Button button;

public void Transition()
{
	var sceneInfo = new LoadSceneInfoName(targetScene);

	if (cache == null)
	{
		cache = transitionScene;
	}

	SceneManagerSingleton.Instance.Loader.TransitionToScene(sceneInfo, new LoadSceneInfoName(cache), UnityEngine.SceneManagement.SceneManager.GetActiveScene());
	button.interactable = false;
}
```

Therefore, I'm reopening the issue to either fix the multiple `AssetReference` scene load issue or replace it internally with the addressable runtime address, since we've observed that it works. Additionally, I'll be adding tests to assert this behavior to avoid similar issues in the future.

A bit off-topic, is that repro project you sent a minimal reproduction environment, or were you testing out the package? That made me consider including a sample to demonstrate the package's features. There were sample scenes in the past, but they were removed at v2.x IIRC.

**Comment by miltoncandelero** [comment]
The story of how I made that is quite curious 😅

(Short answer: it's a repro environment)

I started with only scene A and B, but the transition method wouldn't close A since there was no transition scene, B didn't load yet and unity won't close the last scene

So I made the bootstrapper to have an "always alive" scene, I could quickly transition between A and B... But the bug wasn't happening.

I added a transition scene with manual state flagging (pretending to be a fade or something like that)... Bug wasn't happening.

I made the bootstrapper unload itself after going into A since now with the transition scene, A can be unloaded. Also, it's the setup I have in the project where I found the bug...

Still, no bug.

I thought that maybe my addresables are too empty and I am not getting enough time to trigger the bug, so I grabbed random fbx from the internet, split them into the packs... Still no bug.

Really confused, I looked at "what is my code doing different than my repo?"... In my project the transition lives in the singleton, and not in the behaviour that triggers the change. It has to be that!

And it was.

And then I was too lazy to remove the fbx and other stuff 😅

**Comment by thatjoaoguy** [comment]
I've been there before haha 😅 

> I started with only scene A and B, but the transition method wouldn't close A since there was no transition scene, B didn't load yet and unity won't close the last scene

This is probably an issue I'd want to avoid too. When that's the case, I can create a temporary empty scene just for the sake of transitioning between A and B.
I've never really used the package _without a bootstrapper_ scene, so I was totally biased on that 😅 

Also, I have tests where I load the same scene multiple times, but never tested loading them through their `AssetReference`:
```cs
static readonly ILoadSceneInfo[][] _loadSceneInfos_multiple = new ILoadSceneInfo[][]
{
    new ILoadSceneInfo[]
    {
        new LoadSceneInfoName(SceneBuilder.SceneNames[1]),
        new LoadSceneInfoName(SceneBuilder.SceneNames[2]),
        new LoadSceneInfoName(SceneBuilder.SceneNames[3]),
    },
    new ILoadSceneInfo[]
    {
        new LoadSceneInfoName(SceneBuilder.SceneNames[1]),
        new LoadSceneInfoName(SceneBuilder.SceneNames[1]),
        new LoadSceneInfoName(SceneBuilder.SceneNames[1]),
    }
};
```

I'll get back to work on that to generate a PR soon.

**Comment by thatjoaoguy** [comment]
And there it is, at `AssetReference.cs` at line 240 (as of Addressables `2.1.0`):

```cs
public virtual AsyncOperationHandle<SceneInstance> LoadSceneAsync(LoadSceneMode loadMode = LoadSceneMode.Single, bool activateOnLoad = true, int priority = 100)
{
    AsyncOperationHandle<SceneInstance> asyncOperationHandle = default(AsyncOperationHandle<SceneInstance>);
    if (m_Operation.IsValid())
    {
        Debug.LogError("Attempting to load AssetReference Scene that has already been loaded. Handle is exposed through getter OperationHandle");
    }
    else
    {
        asyncOperationHandle = Addressables.LoadSceneAsync(RuntimeKey, loadMode, activateOnLoad, priority);
        OperationHandle = asyncOperationHandle;
    }

    return asyncOperationHandle;
}
```

The `AssetReference` object caches by design the internal asset loading `AsyncOperationHandle`, directly linking the operation to it. That prevents us from attempting to load multiple instances of the same asset (preventing memory duplication) unless we load through the `Addressables` API by using its address (runtime key). It's a safety mechanism for loading assets, but since the standard scene operations can load the same scene multiple times (and you just accidentally ran into this issue), it would make sense to support this functionality for addressable scenes as well.

However, when unloading the scene, there's no way to correlate an `AssetReference` with a loaded scene if it was loaded through the `Addressables` API since the `AssetReference` object will have an invalid `AsyncOperationHandle`.

I'll see if I can add a logic in the middle that glues together the `AssetReference` with a scene loaded through regular `Addressable` API.

**Comment by thatjoaoguy** [comment]
I'm providing a few insights into what I'm planning to bring with the fix to this issue.

In the current version of the package (2.x), we have a separation of Addressable and non-Addressable scene managers due to some specifics on their load/unload operations. If we abstract those specifics, we could eliminate this separation and have a single scene manager to load/unload and keep track of loaded scenes without worrying about where they come from.

Since the original issue is related to the lack of a link between an `ILoadSceneInfo` and its loaded scene, I plan to hard-link these structures in an abstracted layer so we can manage all types of scenes in a single scene manager class.

In short, my initial experiment is something like:

```cs
// Interface to abstract the load scene operation differences between addressable and non-addressable scenes
public interface ILoadSceneOperation
{
    float Progress { get; }
    bool IsDone { get; }

    Scene GetResult();
}

// Interface to abstract the link between an ILoadSceneInfo, its loading operation and the final loaded scene
public interface ISceneData
{
    ILoadSceneOperation LoadOperation { get; }
    ILoadSceneInfo LoadSceneInfo { get; }
    Scene LoadedScene { get; }
}
```

To the end user, the only change is that they will be able to use a single scene manager for both addressable and non-addressable scenes. All these changes will be performed in the internal workings of the scene manager. I'm still experimenting with this approach, but so far I think it's very promising.

**Comment by thatjoaoguy** [comment]
## **IT WORKED**!

I've created an additional scene manager (temporarily called `NewSceneManager`) to test this new behavior and added it to my existing scene manager tests. The result was that the **new scene manager passed all tests**, including the test to reproduce this very issue:

![image](https://github.com/mygamedevtools/scene-loader/assets/9505905/1f193a41-5678-4bcd-9443-048de9d28c35)

In the image, you can see that all tests have passed, except for this issue's reproduction test which expectedly fails when using the current scene manager, but succeeds when using the new implementation. All tests are parametrized to test all 3 implementations of the scene manager.

### Other advantages of the new implementation

It allows the unification of the addressable and non-addressable workflows seamlessly. That means we no longer need two scene managers (`SceneManager` and `SceneManagerAddressable`), just one. It simplifies the way we deal with the scene loaders and also the tests.

### Next Steps

I'll still need to further test the new implementation with the scene loaders. After getting it all to work, I'll **remove** the `SceneManagerAddressable` implementation and update the `SceneManager` with the new implementation. Since this is a breaking change, the next package version will be bumped to 3.x. Also, I'll have to update the documentation to reflect the new changes.

Another thing that I'm considering is, since now we no longer need to separate the scene workflows, to use the scene loader as a wrapper to the unity scene manager. So maybe, when creating a scene manager, you could pass a bool flag to say whether you want it to include the already loaded scenes in its management. This removes the need to have the `externalScene` parameter in the scene loaders.

**Comment by thatjoaoguy** [comment]
A prerelease version `3.0.0-pre.12` has been released and fixes this issue. I'm in the process of updating the documentation and writing a migration guide, but you can try out the new version if you want. A few tips:

```cs
// Replace SceneManager with AdvancedSceneManager
ISceneManager sceneManager = new AdvancedSceneManager();

// Alternatively, if you want to include the currently loaded scenes into the scene manager on initialization, 
// you can provide a bool argument to the constructor. This removes the need to pass the externalOriginScene
// in the former implementation.
ISceneManager sceneManager = new AdvancedSceneManager(true);

// The scene loader implementation does not change
ISceneLoaderAsync sceneLoader = new SceneLoaderAsync(sceneManager);

// Then, for loading scenes as you were doing before:
ILoadSceneInfo sceneInfo = new LoadSceneInfoAssetReference(targetScene);
ILoadSceneInfo cacheInfo = new LoadSceneInfoAssetReference(transitionSceneAddressable);

sceneLoader.TransitionToScene(sceneInfo, cacheInfo);

// Now you can also, if you need, mix between addressable and non-addressable scenes, for example
ILoadSceneInfo targetInfo = new LoadSceneInfoAssetReference(targetScene);
ILoadSceneInfo loadingInfo = new LoadSceneInfoIndex(1);

sceneLoader.TransitionToScene(targetInfo, loadingInfo);
```

I'll let you know when the documentation is done. Meanwhile, let me know if you have any doubts in case you want to try the preview update.

**Comment by miltoncandelero** [comment]
Sorry I disappeared so suddenly, everything changed when the delivery nation attacked. 🥲 

I am trying v3 now, really smooth sailing! I also love the unified manager and (soon to be?) unified async loader!

Thanks a lot for your hard work <3
