### ISSUE TITLE
First scene does not unload during transition if it's the only scene loaded and no transition scene is provided

### ISSUE THREAD

**Issue by thatjoaoguy** [mygamedevtools/scene-loader#35]
> I started with only scene A and B, but the transition method wouldn't close A since there was no transition scene, B didn't load yet and unity won't close the last scene

Originally reported at [#34](https://github.com/mygamedevtools/scene-loader/issues/34#issuecomment-2136247884) by @miltoncandelero

I assume the solution would be to create a temporary empty scene when that's the case.

**Comment by VirtualMaestro** [comment]
Just now, I've faced this bug and thought that I didn't get the documentation about the TransitionToScene.
My usual flow is:
- Loader scene. It contains something like a progress bar (just an image) and a camera. The main purpose is to initialize a framework (push some parts to DontDestroyOnLoad) and load config file(s).
- After all preparations are done, it loads 'Main menu scene' (basically, here starts the game) and gets deleted.

Some code that I use now:
``` csharp
private static readonly ILoadSceneInfo GameSceneInfo = new LoadSceneInfoName("Assets/Client/Scenes/Game.unity");
private static readonly ILoadSceneInfo MenuSceneInfo = new LoadSceneInfoName("Assets/Client/Scenes/Menu.unity");
.......
_sceneManager = new SceneManagerAddressable();
_asyncSceneLoader = new SceneLoaderAsync(_sceneManager);
......
private void _OnConfigFileLoaded()
{
	_asyncSceneLoader.Manager.SceneLoaded += _OnSceneLoaded;
	_asyncSceneLoader.LoadScene(MainSceneInfo, true);
}

private void _OnSceneLoaded(Scene scene)
{
        // Standard Unity's scene manager. 
	SceneManager.UnloadSceneAsync(0); // removes the 'Loader.unity' - the only scene that is in the Build settings.
}
```

Another question. Does it take into account only scene name (e.g. 'Menu.unity') or full path ("Assets/Client/Scenes/Menu.unity") ? 
It is important to know since it is possible to have similar scene names but in different packages.

Thank you)

**Comment by thatjoaoguy** [comment]
Hey @VirtualMaestro thank you for adding your insights on this. I'll be working on this shortly after #34.

To answer your question, it works for **both** the scene name and path, according to the [SceneManager.LoadSceneAsync](https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.LoadSceneAsync.html) documentation. For addressable scenes, then it needs to be the full address.

In your case, considering you don't have scenes with the same name, you could replace:
```diff
-private static readonly ILoadSceneInfo GameSceneInfo = new LoadSceneInfoName("Assets/Client/Scenes/Game.unity");
-private static readonly ILoadSceneInfo MenuSceneInfo = new LoadSceneInfoName("Assets/Client/Scenes/Menu.unity");
+private static readonly ILoadSceneInfo GameSceneInfo = new LoadSceneInfoName("Game");
+private static readonly ILoadSceneInfo MenuSceneInfo = new LoadSceneInfoName("Menu");
```
