### ISSUE TITLE
Unable to link all scene datas to loaded scenes. Linked 0/1

### ISSUE THREAD

**Issue by VirtualMaestro** [mygamedevtools/scene-loader#40]
After the upgrade to the vesion 3.0 I'm getting this error:
Unable to link all scene datas to loaded scenes. Linked 0/1.

Unable to link all scene datas to loaded scenes. Linked 0/1.
UnityEngine.Debug:LogError (object)
MyGameDevTools.SceneLoading.SceneDataUtilities:LinkLoadedScenesWithSceneDataArray (MyGameDevTools.SceneLoading.ISceneData[],System.Collections.Generic.IList`1<MyGameDevTools.SceneLoading.ISceneData>) (at ./Library/PackageCache/com.mygamedevtools.scene-loader@b0a767ef89/Runtime/Utilities/SceneDataUtilities.cs:72)
MyGameDevTools.SceneLoading.AdvancedSceneManager/<LoadScenesAsync_Internal>d__30:MoveNext () (at ./Library/PackageCache/com.mygamedevtools.scene-loader@b0a767ef89/Runtime/AdvancedSceneManager.cs:199)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

All scenes are added to the Build Settings.
```csharp
        private static readonly ILoadSceneInfo MainSceneInfo = new LoadSceneInfoName("Assets/Client/Scenes/Main.unity");

        private ISceneManager _sceneManager = new AdvancedSceneManager();
        private ISceneLoader _asyncSceneLoader = new SceneLoaderAsync(_sceneManager);

            _asyncSceneLoader.Manager.SceneLoaded += _OnSceneLoaded;
            _asyncSceneLoader.LoadScene(MainSceneInfo, true);

        private void _OnSceneLoaded(Scene scene)
        {}
```

Thanks

**Comment by thatjoaoguy** [comment]
Hi @VirtualMaestro, thank you for reporting this issue.

At first glance, it looks like the issue is related to loading the scene by its **path**. Did you try to load the scene by its **name** instead?

I think the package does not test loading scenes by path. I'll check whether that's the case and take a closer look at your report later today.

**Comment by VirtualMaestro** [comment]
I don't know if it should work now with the latest 3.0 version, but it definitely worked with the previous version 2.x.

**Comment by thatjoaoguy** [comment]
Yeah, since `3.0` introduced "scene linking", now the loaded scenes must be matched with their load scene info. In `2.x` that was the case only for addressable scenes.

Loading a scene by its path should work, so this is definitely a bug.

When linking the loaded scene, as of `3.0.0`, it only [compares the `ILoadSceneInfo` reference to the scene name, not the path](https://github.com/mygamedevtools/scene-loader/blob/b8167bd7ec0f0fe20abde7a23063cbbb5e45ba30/Packages/com.mygamedevtools.scene-loader/Runtime/Structs/LoadSceneInfoName.cs#L29).
```cs
namespace MyGameDevTools.SceneLoading
{
    public readonly struct LoadSceneInfoName : ILoadSceneInfo
    {
        // [...]
        public bool CanBeReferenceToScene(Scene scene) => scene.name == _sceneName;
        // [...]
    }
}
```

I believe that the fix is just adding a comparison to the `scene.path` as well, but I need to add tests to ensure that this is a reliable behavior.

**Comment by thatjoaoguy** [comment]
I have successfully reproduced the issue with updates to the Play Mode Tests. By simply adding `LoadSceneInfoName` with the scene path in the tests, they started to fail and log the same output you reported.

![image](https://github.com/user-attachments/assets/dd433df6-62ab-414e-b679-e82bfe03e9b3)

Then, after applying the suggested fix from the previous comment, it worked:

```diff
-        public bool CanBeReferenceToScene(Scene scene) => scene.name == _sceneName;
+        public bool CanBeReferenceToScene(Scene scene) => scene.name == _sceneNameOrPath || scene.path == _sceneNameOrPath;
```

![image](https://github.com/user-attachments/assets/dd97db94-174f-4a2a-9d32-005a9e584ec8)

If the tests succeed in the MR pipeline, then a fix will be deployed today.
